config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'login', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
#every new class will inheret from ApplicationRecord which is what that syntax means
class Article < ApplicationRecord
belongs_to :user
has_many :article_categories
has_many :categories, through: :article_categories
validates :title, presence: true, length: {minimum: 2, maximun: 100}
validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
before_save {self.email = email.downcase}
has_many :articles, dependent: :destroy
validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
helper_method :current_user, :logged_in?
    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        end
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    # this helper will run the method set_article before any of the code in the mentioned methods is run
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    
    #to display the article corresponding to the id in the url
    def show
    end
    #main page that displays all the articles
    def index
        @articles = Article.all
    end
    #page where new article gets created and saved to a variable. initialize the 
    # variable so if it errors out and relouds theres no error on page
    def new
        @article = Article.new
    end
    # page for editing article
    def edit
    end
    #create method to save created article to db, redirect to diff page
    def create
      @article = Article.new(article_params)
      @article.user = current_user
      if @article.save
        flash[:notice] = "Article was created successfully."
      redirect_to @article
      else
        render 'new'
      end
    end
    # update exisitng article in db
    def update
         if @article.update(article_params)
         flash[:notice] = "Article was updated successfully!"
         redirect_to @article
        else
            render 'edit'
         end
    end
    #delete article
    def destroy
        @article.destroy
        redirect_to articles_path
    end

    #anything put inside the private block will only be avalible to this controller, not outside it
    private
    def set_article
    @article = Article.find(params[:id])
    end
    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end
    def require_same_user
      if  current_user != @article.user
        flash[:alert] = "You can only edit or delete your own article"
        redirect_to @article
      end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_user, except: [:show, :index]

    def index
        @categories = Category.all
    end
    def new
        @category = Category.new
    end
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category successfully created"
            redirect_to categories_path
        else
            render "new"
        end
    end
    def show
        @category = Category.find(params[:id])
    end

    private
    def category_params
        params.require(:category).permit(:name)
    end
  
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end
    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in successfully!"
            redirect_to user
        else
            flash.now[:alert] = "Entered wrong email or password, Try again"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged Out"
        redirect_to articles_path
    end

end

app/controllers/users_controller.rb
class UsersController <  ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

def show
    @articles = @user.articles
end
def index
    @users = User.all
end
def new
 @user = User.new   
end
def create
@user = User.new(user_params)
if @user.save
    session[:user_id] = @user.id
    flash[:notice] = "Successful Signup!"
    redirect_to @user
else
    render 'new'
end
end

def edit
end

def update
    if @user.update(user_params)
        flash[:notice] = "Your account was successfuly updated!"
        redirect_to @user
    else
        render "edit"
    end
end

def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to users_path
end

private
def user_params
    params.require(:user).permit(:username, :email, :password)
end
def set_user
    @user = User.find(params[:id])
end
def require_same_user
    if  current_user != @user
      flash[:alert] = "You can only edit your own profile"
      redirect_to @user
    end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
    # helper method for gravatar
    def gravatar_for (user, options = {size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "mt-3 rounded-circle shadow")
    end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-sm-10 text-center">

            <% @articles.each do |article| %>
            <div class="card text-center mb-4 article-card">
                <div class="card-header text-muted">
                    written by <%= article.user.username %>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= article.title %></h5>
                    <p class="card-text"><%= truncate(article.description, length: 100) %></p>
                    <%= link_to 'View', article_path(article.id), class: "btn btn-primary" %>
                    <% if logged_in? && article.user == current_user %>
                        <%= link_to 'Edit', edit_article_path(article.id), class: "btn btn-primary" %>
                        <%= link_to 'Delete', article_path(article.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>
                    <% end %>
                </div>
                <div class="card-footer text-muted">
                    Created <%= time_ago_in_words(article.updated_at) %> ago
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/articles/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-10">

         <%= render 'shared/errors', obj: @article %>
            <div class="card text-center mt-5 p-4">

                <%= form_with(model: @article, local: true) do |f| %>
                <div class="form-group row">
                    <%= f.label :title, class: "col-sm-3 col-form-label" %><br/>
                    <div  class="col-8 mb-3">
                    <%= f.text_field :title, class: "form-control" %>
                    </div>
                </div>

                <div class="form-group row">
                    <%= f.label :description, class: "col-sm-3 col-form-label" %><br/>
                    <div  class="col-8">
                    <%= f.text_area :description, rows: 10, class: "form-control" %>
                    </div>
                </div>

                <div class="form-group row">
                    <%= f.label :category, class: "col-sm-3 col-form-label" %><br/>
                    <div  class="col-8">
                        <%= f.collection_select(:category_ids, Category.all, :id, :name, {prompt: "Select Categories"},
                        {multiple: true, class: "form-select mt-3"}) %>
                    </div>
                </div>
            </div>



                <div class="form-group mt-3 text-end">
                    <%= f.submit class: "btn btn-outline-primary" %>
                </div>
                
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1  class="text-center mt-4">Edit Article</h1>

<%= render 'form' %>

<div class="text-center mt-4">
    <%= link_to 'Cancel and return to Article Listing', articles_path, class: "btn btn-primary" %>
 </div>

app/views/articles/index.html.erb
<h1 class="text-center mt-4 mb-4">Articles</h1>
<p class="text-center">
    <%= link_to 'New Article', new_article_path, class: "btn btn-outline-primary mb-4" %>
</p>
<%= render 'article'%> 

app/views/articles/new.html.erb
<h1  class="text-center mt-4">New Article</h1>

<%= render 'form' %>

<div class="text-center mt-4">
    <%= link_to 'Return to Article Listing', articles_path, class: "btn btn-primary" %>
 </div>

app/views/articles/show.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-sm-10">
            <div class="card text-center mt-5 p-4 article-card">
                <h1><%= @article.title %></h1>
                    <div class="card-body">
                        <p><%= @article.description %></p>
                       
                        <% @article.categories.each do |cat| %>
                            <div class="badge rounded-pill bg-info mb-3"><%= cat.name %></div>
                            <% end %>
                            <br/>
                            <% if logged_in? && @article.user == current_user %>
                                <%= link_to 'Edit', edit_article_path(@article), class:"btn btn-primary" %>
                                <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-primary" %> <br/>
                            <% end %>
                            <%= link_to 'Return to Article Listing', articles_path, class:"btn btn-primary mt-3" %>
                    </div>
            </div>

        </div>
    </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4 mb-4">Categories</h1>
<p class="text-center">
    <%= link_to 'Create New Category', new_category_path, class: "btn btn-outline-primary mb-4" %>
</p>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-sm-10 text-center">

            <% @categories.each do |category| %>
            <div class="card text-center mb-4 p-3 article-card">
                <h3> <%= link_to category.name, category_path(category) %> </h3>
                <p class="text-muted">Created <%= time_ago_in_words(category.created_at) %> ago </p>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/categories/new.html.erb
<h1  class="text-center mt-4">Create a new Category</h1>

<div class="container">
    <div class="row justify-content-center">
    <div class="col-sm-8">

    <%= render 'shared/errors', obj: @category %>

    <div class="card text-center mt-5 p-4">

                <%= form_with(model: @category, local: true) do |f| %>
                <div class="form-group row">
                    <%= f.label :name, "Category Name", class: "col-sm-3 col-form-label" %><br/>
                    <div  class="col-8 mb-3">
                    <%= f.text_field :name, class: "form-control" %>
                    </div>
                </div>

            </div>

                <div class="form-group mt-3 text-end">
                    <%= f.submit class: "btn btn-outline-primary" %>
                </div>
                
                <% end %>
            </div>
        </div>
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-sm-10">
            <div class="card text-center mt-5 p-4 article-card">
                <h1><%= @category.name %></h1>
                    <div class="card-body">
                            <%= link_to 'Return to Category Listing', categories_path, class:"btn btn-primary mt-3" %>
                    </div>
            </div>

        </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" data-bs-target="#my-alert" aria-label="Close"></button>    
    </div>
  <% end %> 
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'BLOG', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <div class="navbar-nav">

        <% if logged_in? %>
          <div class="nav-item">
            <%= link_to 'Logout', login_path, class: "nav-link", method: :delete %>
          </div>

        <% else %>

          <div class="nav-item">
            <%= link_to 'Login', login_path, class: "nav-link" %>
          </div>

        <% end %>

        <div class="nav-item">
          <%= link_to 'Articles', articles_path, class: "nav-link" %>
        </div>

        <div class="nav-item">
          <%= link_to 'About', about_path, class: "nav-link" %>
        </div>

        <div class="nav-item">
        <%= link_to 'Bloggers', users_path, class: "nav-link" %>
        </div>

        <div class="nav-item">
        <%= link_to 'Categories', categories_path, class: "nav-link" %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-sm-10">
            <div class="card text-center mt-5 p-4 article-card">
                <h1>About the Blog</h1>
                    <div class="card-body">
                        <p>Welcome to the blog!</p>

                            <%= link_to 'Articles Listing', articles_path, class:"btn btn-primary" %>
                            <%= link_to 'Home Page', root_path, class:"btn btn-primary" %>
                    </div>
            </div>

        </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="container text-center">
    <div class="card mt-5 home-hero">
        <div class="hero-text">
            <h1 class="display-1 font-weight-bold">Rails Blog</h1>
            <button type="button" class="btn btn-dark btn-lg"><%= link_to 'Articles Listing', articles_path %></button>
            <button type="button" class="btn btn-dark btn-lg"><%= link_to 'Sign up', signup_path %></button>
        </div>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>

<div class="alert alert-danger alert-dismissible fade show" role="alert">
<p> The following errors prevented the <%= obj.class.name.downcase %> from being saved</p>
    <% obj.errors.full_messages.each do |error| %>
        <%= error %><br/>
    <% end %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" data-bs-target="#my-alert" aria-label="Close"></button>    
</div>


<% end %>

app/views/users/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
    <div class="col-sm-8">

    <%= render 'shared/errors', obj: @user %>

    <div class="card text-center mt-5 p-4">

                <%= form_with(model: @user, local: true) do |f| %>
                <div class="form-group row">
                    <%= f.label :username, class: "col-sm-3 col-form-label" %><br/>
                    <div  class="col-8 mb-3">
                    <%= f.text_field :username, class: "form-control" %>
                    </div>
                </div>

                <div class="form-group row">
                    <%= f.label :email, class: "col-sm-3 col-form-label" %><br/>
                    <div  class="col-8 mb-3">
                    <%= f.email_field :email, class: "form-control" %>
                    </div>
                </div>

                <div class="form-group row">
                <%= f.label :password, class: "col-sm-3 col-form-label" %><br/>
                <div  class="col-8">
                <%= f.password_field :password, class: "form-control" %>
                </div>
            </div>

                <div class="form-group mt-3 text-end">
                    <%= f.submit(@user.new_record? ? "Sign Up" : "Update Profile", class: "btn btn-outline-primary") %>
                </div>
                
                <% end %>
            </div>
        </div>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1  class="text-center mt-4">Edit your Profile</h1>

<%= render 'form' %>

<div class="text-center mt-4">
    <%= link_to 'Return to Article Listing', articles_path, class: "btn btn-primary" %>
 </div>

app/views/users/index.html.erb
<h1 class="text-center mt-4 mb-4">Our Bloggers</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-sm-10 text-center">
            <%= link_to 'Sign up for an Account', signup_path, class: "btn btn-secondary mb-4" %>

            <% @users.each do |user| %>
            <div class="card text-center mb-4 article-card">
                <div class="card-header text-muted">
                    written by <%= link_to user.username, user %>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= link_to gravatar_for(user, size: 150), user %></h5>
                    <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
                    <%= link_to 'View Profle', user, class: "btn btn-primary" %>
                    <% if logged_in? && user == current_user %>
                        <%= link_to 'Edit Profile', edit_user_path(user), class: "btn btn-primary" %>
                    <% end %>
                </div>
                <div class="card-footer text-muted">
                    Joined <%= time_ago_in_words(user.created_at) %> ago
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<h1  class="text-center mt-4">Sign Up</h1>

<%= render 'form' %>

<div class="text-center mt-4">
    <p>Already have an account?</p>
    <%= link_to 'Login', login_path, class: "btn btn-primary" %>
 </div>

app/views/users/show.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-10 text-center mb-4">
            <h1 class="mt-4"><%= @user.username %>'s Profile</h1>
            <% if logged_in? && @user == current_user %>
                <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-outline-primary btn-sm mb-3" %><br/>
                <%= link_to 'Delete Profile', user_path(@user), class: "btn btn-outline-danger btn-sm", method: :delete, data: {confirm: "Are you sure?"} %><br/>
            <% end %>
            <%= gravatar_for @user, size: 200 %>

        </div>
    
        <h3 class="text-center mb-3"> My Articles</h3>
        <% if logged_in? && @user == current_user %>
            <p class="text-center">
                <%= link_to 'New Article', new_article_path, class: "btn btn-outline-primary mb-4" %>
            </p>
        <% end %>

        <%= render 'articles/article' %>

    </div>
</div>